### ISSUE TITLE
OS 4.4.4 Back Camera Fails

### ISSUE THREAD

**Issue by yo1989** [sandrios/sandriosCamera#21]
Hi,

It's a great library,. Works perfectly fine in higher end devices. In OS 4.4.4 back camera opens, but while triggering it gets stuck. but screen will be active. We can change into front camera and continue. But Back camera fails to capture.

On tapping capture button twice it give below exception.
  java.lang.RuntimeException: takePicture failed
 at android.hardware.Camera.native_takePicture(Native Method)
 at android.hardware.Camera.takePicture(Camera.java:1312)
 at android.hardware.Camera.takePicture(Camera.java:1257)
 at com.sandrios.sandriosCamera.internal.manager.impl.Camera1Manager$3.run(Camera1Manager.java:118)
 at android.os.Handler.handleCallback(Handler.java:733)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:136)
 at android.os.HandlerThread.run(HandlerThread.java:61)

I tried to debug but unable to fix it. Please reply soon.

**Comment by arpitgandhi9** [comment]
Thank you for using the library.
Hope your problem is fixes in version 1.1.0..
Coming soon.!
