### ISSUE TITLE
Lib you use for permission crashes when called from within activity that extends appcompat.

### ISSUE THREAD

**Issue by MrBIMC** [sandrios/sandriosCamera#26]
new SandriosCamera()....launchCamera() crashes when launched inside of class that extends appcompat activity. 

That's a problem of lib you use for permissions. It's known bug there and it's there for more than a year without resolution. So, please, either switch off to any other permission lib (dexter is the most famous and consistent one) or just make developers to ask for permissions themselves before starting a camera instance. 

here's my error log:

```
08-10 22:36:33.890 21043-21043/org.tingr.teacher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.tingr.teacher, PID: 21043
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tingr.teacher/com.gun0912.tedpermission.TedPermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2742)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6178)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                    Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:354)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.onPostCreate(AppCompatDelegateImplV9.java:170)
                                                                       at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:97)
                                                                       at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2663
```

**Comment by JosephM3388** [comment]
I am getting this error too. Did you find a work around this bug?

**Comment by MrBIMC** [comment]
yes, I did! But it required some changes in the code of the lib. Author still haven't accepted my pullrequest with fixes, so I hosted my fork on the jitpack.

here's the link with details:

https://github.com/MrBIMC/sandriosCamera

**Comment by JosephM3388** [comment]
Cool thank you for taking the time to fix this! What should I do in this case? I read your README, and it seems like all I need to do is follow your three steps and the permissions should work now?

**Comment by MrBIMC** [comment]
yeah, just replace his reference with mine and everything should start working.

**Comment by JosephM3388** [comment]
I keep getting this error:  
                                                                  `Caused by: java.lang.ClassCastException: io.github.memfis19.annca.internal.ui.view.AspectFrameLayout cannot be cast to com.sandrios.sandriosCamera.internal.ui.view.AspectFrameLayout
`

**Comment by MrBIMC** [comment]
hmm. did you do clean build?

I'm launching studio will answer back in a couple of minutes.

**Comment by JosephM3388** [comment]
Yes, I did. I am not sure if it has to do with my imports?

**Comment by MrBIMC** [comment]
ok, for me everything works correctly. I'm pretty sure there's something wrong with your stuff as clearly io.github.memfis19.annca.internal.ui.view.AspectFrameLayout  should not exist as it's internal matter of com.sandrios.sandriosCamera.internal.ui.view.AspectFrameLayout.

**Comment by JosephM3388** [comment]
Looking into, I'll report back if I fix this. Thank you for your help.

**Comment by arpitgandhi9** [comment]
Apologies for the late response with this, had a lot on my plate.
Please check the releases page for updates.
Please also check readme for updated instructions.
Thank you for awesome response.

**Comment by arpitgandhi9** [comment]
I am also planning to add UI for picker like whatsapp with swipe and filters for image.. Stay tuned guys.
