### ISSUE TITLE
java.lang.IllegalStateException: Handler (android.os.Handler) sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by kosmonastya** [sandrios/sandriosCamera#3]
Hi and thanks for such a nice library! Checked this out today and saw the issue

Steps to reproduce:

- .setShowPicker(true)
- launch SandriosCamera with picker
- tap on any of previews

`01-05 17:58:57.256 22321-22641/? W/MessageQueue: Handler (android.os.Handler) {3a72e4e} sending message to a Handler on a dead thread
                                                 java.lang.IllegalStateException: Handler (android.os.Handler) {3a72e4e} sending message to a Handler on a dead thread
                                                     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                     at android.os.Handler.enqueueMessage(Handler.java:631)
                                                     at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                     at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                     at android.os.Handler.post(Handler.java:326)
                                                     at android.hardware.camera2.impl.CameraDeviceImpl.close(CameraDeviceImpl.java:1010)
                                                     at com.sandrios.sandriosCamera.internal.manager.impl.Camera2Manager.closeCameraDevice(Camera2Manager.java:463)
                                                     at com.sandrios.sandriosCamera.internal.manager.impl.Camera2Manager.closeCamera(Camera2Manager.java:442)
                                                     at com.sandrios.sandriosCamera.internal.manager.impl.Camera2Manager.access$600(Camera2Manager.java:53)
                                                     at com.sandrios.sandriosCamera.internal.manager.impl.Camera2Manager$4.run(Camera2Manager.java:225)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)`

Exception is handled, but will be good to fix.
Device - Nexus 5, Android 6.0.1

**Comment by aftabsikander** [comment]
> Exception is handled, but will be good to fix.
Device - Nexus 5, Android 6.0.1

@kosmonastya  I have the same device, I am unable to produce this issue. Can you please confirm which version you are using. Because I have tested this on various device. It would be great If you provide a sample project in which this issue is getting produced.

**Comment by kosmonastya** [comment]
Was using 1.0.7

Created an empty project with just a button to call the lib - works like a charm, but in my big project - same issue. Give me a day, I'll try to find watta hell and report here then

**Comment by arpitgandhi9** [comment]
I do not have a Nexus 5 Device. But I tried with other Samsung and Moto Devices running 6.0.1 and was unable to reproduce the error.

PS: You do not need to manage permissions as done in the sample app, The library does that for you.

**Comment by kosmonastya** [comment]
Well, looks like not a major issue. I'll try to research a bit more, but
let's close it for now!

P.S. Thanks, I didn't notice the thing abt permissions ☺️

**Comment by mwshubham** [comment]
This might be related to the issue. Steps to reproduce the problem:
1. Load a fragment with CameraFragment
2. Now open a camera activity.
3. Close/Destroy the camera activity.
4. PROBLEM: Camera fragment doesn't behave properly as background thread is stopped. 

Workaround:

```
File : CameraManager

boolean isBackgroundThreadStoped();

File: BaseCameraManager

 public boolean isBackgroundThreadStoped() {
        return backgroundThread == null;
}

```


```
File: Camera1Controller and 
  @Override
    public void onResume() {
        Log.i(TAG, "onResume: ");
        if (cameraManager.isBackgroundThreadStoped()) {
            cameraManager.initializeCameraManager(configurationProvider, cameraView.getActivity());
        }
        cameraManager.openCamera(currentCameraId, this);
    }


File: Camera2Controller
  @Override
    public void onResume() {
        if (camera2Manager.isBackgroundThreadStoped()) {
            camera2Manager.initializeCameraManager(configurationProvider, cameraView.getActivity());
        }
        camera2Manager.openCamera(currentCameraId, this);
    }
```

```
I/SandriosCameraFragment: onPause: 
I/Camera1Controller: onResume: 
I/Camera1Manager: openCamera: 
I/Camera1Controller: onDestroy: 
I/BaseCameraManager: stopBackgroundThread: 
I/SandriosCameraFragment: onResume: 
I/Camera1Controller: onResume: 
I/Camera1Manager: openCamera: 
E/Camera1Manager: openCamera backgroundHandler is null
D/Camera1Manager: Error starting camera preview: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
D/Camera1Manager: Error starting camera preview: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference

```
