### ISSUE TITLE
 java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by dnsdirmx** [sandrios/sandriosCamera#4]
Error in android 4.4.2 after taking a photo

01-08 21:07:24.126 27827-27827/uv.mx.varappmiento_app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: uv.mx.varappmiento_app, PID: 27827
                                                                        java.lang.OutOfMemoryError
                                                                            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                            at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:645)
                                                                            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:621)
                                                                            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:401)
                                                                            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:427)
                                                                            at com.sandrios.sandriosCamera.internal.imageCropper.CropperView.loadNewImage(CropperView.java:183)
                                                                            at com.sandrios.sandriosCamera.internal.ui.preview.PreviewActivity.showImagePreview(PreviewActivity.java:267)
                                                                            at com.sandrios.sandriosCamera.internal.ui.preview.PreviewActivity.displayImage(PreviewActivity.java:263)
                                                                            at com.sandrios.sandriosCamera.internal.ui.preview.PreviewActivity.onCreate(PreviewActivity.java:226)
                                                                            at android.app.Activity.performCreate(Activity.java:5267)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2239)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5372)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by arpitgandhi9** [comment]
I have added [uCrop](https://github.com/Yalantis/uCrop/) for cropping the image.
So, the issue should not come up again.
