### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 51916812 byte allocation with 

### ISSUE THREAD

**Issue by ably-dheeru** [sandrios/sandriosCamera#46]
USER_COMMENT=null
ANDROID_VERSION=6.0
APP_VERSION_NAME=1.0
BRAND=vivo
PHONE_MODEL=vivo 1601
CUSTOM_DATA=
STACK_TRACE=java.lang.OutOfMemoryError: Failed to allocate a 51916812 byte allocation with 4193552 free bytes and 44MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:433)
at com.sandrios.sandriosCamera.internal.ui.preview.PreviewActivity.rotateImageIfRequired(PreviewActivity.java:412)
at com.sandrios.sandriosCamera.internal.ui.preview.PreviewActivity.onClick(PreviewActivity.java:389)
at android.view.View.performClick(View.java:5272)
at android.view.View$PerformClick.run(View.java:21528)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5790)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1015)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by arpitgandhi9** [comment]
Sorry for the delay. Please update to version 1.2.6
